shift_updates = {
    "Metin Kaya": 15,
    "Melike Öner": 15,
    "Ömer Faruk Korkak": 11,
    "Serkan Aydın": 15,
    "Hakan Sevinç": 14,
    "İsmail Hakkı Yüksel": 15,
    "Lamiya Aliyeva": 17,
    "Mehmet Musab Bal": 9,
    "Necati Karaman": 17,
    "Zeynab Haidara": 13,
    "Numan Mustafa Konuksever": 19,
    "Osman Mert Baş": 19,
    "Özgür Güven": 19,
    "Ayşe Necla Soylu": 19,
    "Sinem Serenay Topsakal": 19,
    "Mustafa Burak Seyhan": 19,
    "Mehmet Sadık Koç": 19,
    "Taha Ersin Çelik": 19,
    "Mehmet Fatih Büyükkuş": 19,
    "Yaşar Can Ersöz": 7,
    "Anıl Aydın": 7,
}

min_doctors_per_area = {1: 1, 2: 1, 3: 1, 4: 2}
